name: Mirror to Codeberg

on:
  push:
    branches:
      - main
      - master

jobs:
  mirror:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout mirror
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Push mirror
        run: |
          git remote add codeberg https://laWiskaPY:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/laWiskaPY/kore.js.git
          git push codeberg --mirror
          git push codeberg HEAD:pages --force